### START STREAM
### moving cars https://www.youtube.com/watch?v=_fDYKDeZC9c
### special place https://www.youtube.com/watch?v=IJSdhfsrnMo
### sai https://www.youtube.com/watch?v=txZATEyGVpA
POST http://127.0.0.1:5000/start

### STOP STREAM
POST http://127.0.0.1:5000/stop

###
POST http://127.0.0.1:5000/process_image

###
GET http://127.0.0.1:5000/getcams

###
POST http://127.0.0.1:5000/addcams
Content-Type: application/json

{
    "email": "ksaisathish@gmail.com",
    "live": true,
    "monitoringStatus": false,
    "name": "Sai Home Camera 2",
    "url": "https://www.youtube.com/watch?v=txZATEyGVpA"
}

###
PUT http://127.0.0.1:5000/updatecam/1
Content-Type: application/json

{
    "id": 1,
    "email": "ksaisathish@gmail.com",
    "live": true,
    "monitoringStatus": false,
    "name": "Sai Home Camera 1",
    "url": "https://www.youtube.com/watch?v=txZATEyGVpA"
}

### Update Monitoring Camera
PUT http://127.0.0.1:5000/updatecam/1
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=IJSdhfsrnMo",
    "email": "muthu892542@gmail.com"
}

### Get all transcripts by camera id
GET http://127.0.0.1:5000/transcripts/1

### Get all transcripts by camera id
GET http://127.0.0.1:5000/transcripts/unusual_activity/1

### alerts
GET http://127.0.0.1:5000/alerts/1
### analytics
GET http://127.0.0.1:5000/analytics
### get chat
GET http://127.0.0.1:5000/chat/1
### chat
POST http://127.0.0.1:5000/chat/3
Content-Type: application/json

{
    "user_query": "can i see humans in the frames?"
}
