### START STREAM
### moving cars https://www.youtube.com/watch?v=_fDYKDeZC9c
### special place https://www.youtube.com/watch?v=IJSdhfsrnMo
### sai https://www.youtube.com/watch?v=txZATEyGVpA
POST http://127.0.0.1:5000/start
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=IJSdhfsrnMo"
}

### STOP STREAM
POST http://127.0.0.1:5000/stop